-- MySQL Script generated by MySQL Workbench
-- 11/22/18 17:55:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Nome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nome` (
  `id` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id` INT NOT NULL,
  `Nome_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Nome_id`),
  INDEX `fk_Funcionario_Nome1_idx` (`Nome_id` ASC),
  CONSTRAINT `fk_Funcionario_Nome1`
    FOREIGN KEY (`Nome_id`)
    REFERENCES `mydb`.`Nome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localização`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localização` (
  `id` INT NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Funcionario_id` INT NOT NULL,
  `Funcionario_Nome_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Funcionario_id`, `Funcionario_Nome_id`),
  INDEX `fk_Localização_Funcionario1_idx` (`Funcionario_id` ASC, `Funcionario_Nome_id` ASC),
  CONSTRAINT `fk_Localização_Funcionario1`
    FOREIGN KEY (`Funcionario_id` , `Funcionario_Nome_id`)
    REFERENCES `mydb`.`Funcionario` (`id` , `Nome_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emitente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emitente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Emitente_Pessoa1_idx` (`Pessoa_id` ASC),
  CONSTRAINT `fk_Emitente_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagador` (
  `id` INT NOT NULL,
  `Valor` DECIMAL(14,2) NOT NULL,
  `Nome_id` INT NOT NULL,
  `Localização_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Nome_id`, `Localização_id`),
  INDEX `fk_Pagador_Nome1_idx` (`Nome_id` ASC),
  INDEX `fk_Pagador_Localização1_idx` (`Localização_id` ASC),
  CONSTRAINT `fk_Pagador_Nome1`
    FOREIGN KEY (`Nome_id`)
    REFERENCES `mydb`.`Nome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagador_Localização1`
    FOREIGN KEY (`Localização_id`)
    REFERENCES `mydb`.`Localização` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recibo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(14,2) NOT NULL,
  `dataemissao` DATE NOT NULL,
  `Emitente_id` INT NOT NULL,
  `Prestador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Recibo_Emitente2_idx` (`Emitente_id` ASC),
  INDEX `fk_Recibo_Prestador1_idx` (`Prestador_id` ASC),
  CONSTRAINT `fk_Recibo_Emitente2`
    FOREIGN KEY (`Emitente_id`)
    REFERENCES `mydb`.`Emitente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_Prestador1`
    FOREIGN KEY (`Prestador_id`)
    REFERENCES `mydb`.`Prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `id` INT NOT NULL,
  `Nome_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Nome_id`),
  INDEX `fk_Funcionario_Nome1_idx` (`Nome_id` ASC),
  CONSTRAINT `fk_Funcionario_Nome1`
    FOREIGN KEY (`Nome_id`)
    REFERENCES `mydb`.`Nome` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ddd` INT NOT NULL,
  `numero` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `Funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefone_Funcionario_idx` (`Funcionario_id` ASC),
  CONSTRAINT `fk_Telefone_Funcionario`
    FOREIGN KEY (`Funcionario_id`)
    REFERENCES `mydb`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emitente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emitente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Emitente_Pessoa1_idx` (`Pessoa_id` ASC),
  CONSTRAINT `fk_Emitente_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prestador_Pessoa1_idx` (`Pessoa_id` ASC),
  CONSTRAINT `fk_Prestador_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recibo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(14,2) NOT NULL,
  `dataemissao` DATE NOT NULL,
  `Emitente_id` INT NOT NULL,
  `Prestador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Recibo_Emitente2_idx` (`Emitente_id` ASC),
  INDEX `fk_Recibo_Prestador1_idx` (`Prestador_id` ASC),
  CONSTRAINT `fk_Recibo_Emitente2`
    FOREIGN KEY (`Emitente_id`)
    REFERENCES `mydb`.`Emitente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_Prestador1`
    FOREIGN KEY (`Prestador_id`)
    REFERENCES `mydb`.`Prestador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoLogradouro` VARCHAR(10) NOT NULL,
  `Logradouro` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(10) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `tipo` INT NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Endereço_Pessoa1_idx` (`Pessoa_id` ASC),
  CONSTRAINT `fk_Endereço_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
